### ISSUE TITLE
Adding pow(), exp() functions

### ISSUE THREAD

**Issue by ibell** [trevorstephens/gplearn#16] opened 2016-06-04 17:55 UTC
I'm interested in adding pow and exponential functions to the set of functions.  Could you please add them?  They are very useful in my fitting routines.

Also, it would be nice if you could describe how you add functions to the library of functions so we could extend it with any function we want.

**Comment by trevorstephens** [comment] 2016-06-04 18:02
Currently you cannot add your own functions without hacking the source code. I'll look into adding this to the next release though. Thanks for the feedback! :+1:

**Comment by ibell** [comment] 2016-06-05 20:00
Yes, not being able to add my own functions makes me quite frustrated.  Would be great if you could make that part more flexible.

**Comment by trevorstephens** [comment] 2016-06-05 20:28
Noted. I'll probably have to change the API a bit for this to work.

Maybe something like `function_set = ['transformer', 'comparison']` as default (rather than having those as first-class `init` parameters) with the option to add your own user-defined functions in that list.

What do you think @ibell ?

**Comment by ibell** [comment] 2016-06-05 22:19
Yes, and it would be great if you could have a custom object with a well-defined API in the ``function_set``.  Something like a term provider class.

Also, I find the term ``transformer`` to not be very descriptive, and you might want to think about a better term if you are changing the API anyway :)

**Comment by trevorstephens** [comment] 2016-06-05 22:25
`transformer` is inherited from scikit-learn terminology. It's not going anywhere :wink:

**Comment by trevorstephens** [comment] 2016-09-03 18:27
Fixed by #18

**Closed** 2016-09-03 18:27 UTC
Labels: enhancement

**Comment by iblasi** [comment] 2017-10-15 18:07
@trevorstephens,
The 0.2.0 release it is perfect to make new functions as solved in issue 18.
However, I find that exponential function encounters some errors that make not achieve a result.
Looking for the following example, where we are looking for a simple exponential equation, the gplearn encounters invalid values in evaluating some functions. This makes fitness to become NaN and the algorithm seem to not converge anywhere.

import numpy as np
from gplearn.genetic import SymbolicRegressor
from gplearn.functions import make_function

def exponent(x):
  return np.exp(x)

X = np.random.randint(0,100,size=(100,3))
y = np.exp(X[:, 0])

X_train , y_train = X[:80,:], y[:80]
X_test , y_test = X[80:,:], y[80:]

exponential = make_function(function=exponent, name='exp', arity=1)
function_set = ['add', 'sub', 'mul', 'div', 'sqrt', 'log',
                'abs', 'neg', 'inv', 'max', 'min', 'sin', 'cos', 'tan', exponential]

est_gp = SymbolicRegressor(population_size=5000,
                           generations=20, stopping_criteria=0.01,
                           function_set=function_set,
                           p_crossover=0.7, p_subtree_mutation=0.1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=0.01, random_state=0)
est_gp.fit(X_train, y_train)
print 'Score: ', est_gp.score(X_test, y_test)
print est_gp._program
```

This code show overflow errors creating NaN fitness as mentioned, and the final result is None

```
    |    Population Average   |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
Meteo_example_1.py:19: RuntimeWarning: overflow encountered in exp
  return np.exp(x)
/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py:1142: RuntimeWarning: invalid value encountered in multiply
  avg = np.multiply(a, wgt, dtype=result_dtype).sum(axis)/scl
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in tan
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in multiply
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in cos
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in sin
  return self.function(*args)
   0    11.09              nan        7              nan              nan     39.42s
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in subtract
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: invalid value encountered in add
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:46: RuntimeWarning: overflow encountered in multiply
  return self.function(*args)
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:111: RuntimeWarning: overflow encountered in divide
  return np.where(np.abs(x2) > 0.001, np.divide(x1, x2), 1.)
   1    11.48              nan       38              nan              nan     44.32s
   2     16.2              nan       10              nan              nan     46.98s
   3    18.69              nan       29              nan              nan     46.91s
   4    21.19              nan       22              nan              nan     46.92s
   5    23.44              nan       25              nan              nan     46.38s
   6    25.52              nan       30              nan              nan     44.79s
   7    27.96              nan       56              nan              nan     43.73s
   8    30.01              nan       44              nan              nan     41.50s
   9    32.29              nan       54              nan              nan     39.10s
  10    34.59              nan       11              nan              nan     36.28s
  11    37.08              nan       18              nan              nan     34.26s
/usr/local/lib/python2.7/site-packages/gplearn/functions.py:128: RuntimeWarning: overflow encountered in divide
  return np.where(np.abs(x1) > 0.001, 1. / x1, 0.)
  12    39.66              nan       34              nan              nan     31.14s
  13    42.05              nan       43              nan              nan     27.39s
  14    43.91              nan       52              nan              nan     23.64s
  15     47.2              nan      118              nan              nan     19.36s
  16    49.95              nan       36              nan              nan     14.88s
  17    52.13              nan        8              nan              nan     10.15s
  18    55.53              nan       21              nan              nan      5.31s
  19    58.17              nan       63              nan              nan      0.00s
Score: 
Traceback (most recent call last):
  File "Meteo_example_1.py", line 69, in <module>
    
  File "/usr/local/lib/python2.7/site-packages/sklearn/base.py", line 388, in score
    multioutput='variance_weighted')
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/regression.py", line 530, in r2_score
    y_true, y_pred, multioutput)
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/regression.py", line 77, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 422, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 43, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by smheidrich** [comment] 2020-10-28 21:00
It's great that user-defined functions now work, but is there any reason why `exp` isn't part of the predefined functions available out of the box? Seems fairly "standard" to me.

**Comment by trevorstephens** [comment] 2020-10-28 21:19
Probably because it would be more likely to get into overflow/closure issues than other functions. You can make it yourself if you need it.

**Comment by smheidrich** [comment] 2020-10-28 21:24
Oh ok, thanks for the clarification!

**Comment by slavust** [comment] 2022-02-12 21:38
Or maybe because it then will try to interpolate with polynomial?
