### ISSUE TITLE
How to limit the memory required by gplearn?

### ISSUE THREAD

**Issue by nicoJiang** [trevorstephens/gplearn#13] opened 2016-04-29 12:37 UTC
I think the gplearn wil use as much memory as possible.
One machine is equipped with 8GB memory.The gplearn eats off 7.85GB and no exception is raised.Everyhing works well.
Another machine has 12GB memory and this time the gplearn consumes 11.8GB.At the last round of the genetic-compution,python is crashed due to a MemoryError.
It's an ironical phenomenon.Why more memory dosen't satisfy the appetite of gplearn instead? 
(PS:The paramters of gplearn are fixed.Both environments are WINDOWS)

**Comment by nicoJiang** [comment] 2016-04-29 14:08
This problem is a little urgent.May you commit a feasible solution as soon as possible?I'll appreciate it a lot!

**Comment by jamartinh** [comment] 2016-04-29 14:30
There is pull request to drop the precious populations. This seems to help
a lot.

**Comment by nicoJiang** [comment] 2016-04-29 14:46
@jamartinh thx a lot

**Comment by trevorstephens** [comment] 2016-04-29 15:35
Closing as this is a duplicate of #5

**Closed by trevorstephens** 2016-04-29 15:35 UTC
